#! /bin/sh

### BEGIN INIT INFO
# Provides:          mailstatsdaemon
# Required-Start:    $syslog $local_fs
# Required-Stop:     $syslog $local_fs
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    Start postfix stats deamon
### END INIT INFO

PIDFILE=/var/run/mailstats.pid
MAILSTAT=/usr/local/share/snmpd-helpers/mail/mailstatsdaemon.pl

test -x $MAILSTAT || exit 0

# Cd to / before starting any daemons.
cd /

case "$1" in
  start)
    echo -n "Starting postfix stats deamon:"
    start-stop-daemon --start --quiet --pidfile $PIDFILE --make-pidfile --background --exec $MAILSTAT
    echo -n " mailstatsdaemon.pl"
    echo "."
    ;;
  stop)
    echo -n "Stopping postfix stats deamon:"
    start-stop-daemon --stop --quiet --pidfile $PIDFILE
    echo -n " mailstatsdaemon.pl"
    echo "."
    ;;
  restart|reload|force-reload)
    echo -n "Restarting postfix stats deamon:"
    start-stop-daemon --stop --quiet --pidfile $PIDFILE
    # We delay a bit to let the daemon exit completely.
    sleep 2
    /bin/rm $PIDFILE
    start-stop-daemon --start --quiet --pidfile $PIDFILE --make-pidfile --background --exec $MAILSTAT
    echo -n " mailstatsdaemon.pl"
    echo "."
    ;;
  *)
    echo "Usage: /etc/init.d/mailstatsdaemon {start|stop|restart|reload|force-reload}"
    exit 1
esac

exit 0
